# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yP8IjHcHFGX6yPz3XmmkkH5twspx2_W_
"""

"""
UAV Distribution Generator - Streamlit Web Application
Author: Masoud Malekzadeh
Date: 2025
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import time
import os
from typing import Optional
import json
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

# Import core modules
from src.llm_generator import LLMDistributionGenerator
from src.uav_system import ModularUAVSystem
from src.visualizations import create_visualizations, create_plotly_visualizations

# Page configuration
st.set_page_config(
    page_title="UAV Distribution Generator",
    page_icon="🚁",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
<style>
    .main-header {
        font-size: 3rem;
        color: #1e3d59;
        text-align: center;
        padding: 1rem;
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        font-weight: bold;
    }
    .sub-header {
        text-align: center;
        color: #666;
        margin-bottom: 2rem;
    }
    .metric-card {
        background-color: #f0f2f6;
        padding: 1rem;
        border-radius: 0.5rem;
        margin: 0.5rem 0;
    }
    .stButton>button {
        width: 100%;
        background-color: #667eea;
        color: white;
        font-weight: bold;
    }
    .stButton>button:hover {
        background-color: #764ba2;
    }
</style>
""", unsafe_allow_html=True)

# Initialize session state
if 'generated' not in st.session_state:
    st.session_state.generated = False
if 'figure' not in st.session_state:
    st.session_state.figure = None
if 'trajectory' not in st.session_state:
    st.session_state.trajectory = None
if 'distribution_name' not in st.session_state:
    st.session_state.distribution_name = None

# Predefined distributions
DISTRIBUTION_EXAMPLES = {
    "Eastern 4x Denser": "Create a distribution where the eastern half (right side) has 4 times higher density than the western half",
    "Center Hotspot": "Make a circular hotspot in the center (within radius 0.3) that is 5 times denser than the outer region",
    "Gaussian": "Create a Gaussian distribution centered at the origin with standard deviation 0.3",
    "Northern 3x": "Make the northern hemisphere 3 times denser than the southern hemisphere",
    "Dual Hotspots": "Create two hotspots: one at angle 0 degrees and one at angle 180 degrees, each within radius 0.4, with 4x density",
    "Ring Pattern": "Make a ring pattern where radius 0.6 to 0.8 has 5 times higher density than other regions",
    "Quadrant Cascade": "Make the first quadrant 2 times the second quadrant, and the second quadrant two times the third and the third four times the fourth",
}

def main():
    # Header
    st.markdown('<h1 class="main-header">🚁 UAV Distribution Generator</h1>', unsafe_allow_html=True)
    st.markdown('<p class="sub-header">Generate and visualize UAV trajectories with AI-powered distribution patterns</p>', unsafe_allow_html=True)

    # Sidebar
    with st.sidebar:
        st.header("⚙️ Configuration")

        # API Configuration
        with st.expander("🔑 API Settings", expanded=True):
            api_key = st.text_input(
                "Groq API Key",
                value=os.environ.get("GROQ_API_KEY", ""),
                type="password",
                help="Get your API key from console.groq.com"
            )
            if api_key:
                os.environ["GROQ_API_KEY"] = api_key

        # Distribution Selection
        st.subheader("📊 Distribution Selection")

        dist_type = st.radio(
            "Choose input method:",
            ["Preset Distributions", "Custom Description"]
        )

        if dist_type == "Preset Distributions":
            selected_preset = st.selectbox(
                "Select a preset:",
                list(DISTRIBUTION_EXAMPLES.keys())
            )
            description = DISTRIBUTION_EXAMPLES[selected_preset]
            st.info(f"📝 {description}")
        else:
            description = st.text_area(
                "Enter custom distribution description:",
                height=100,
                placeholder="Describe the distribution pattern you want..."
            )

        # UAV Parameters
        st.subheader("🎛️ UAV System Parameters")

        col1, col2 = st.columns(2)
        with col1:
            delta = st.slider(
                "Delta (δ)",
                min_value=0.01,
                max_value=0.3,
                value=0.05,
                step=0.01,
                help="Minimum radius for UAV trajectory"
            )

            tau = st.slider(
                "Tau (τ)",
                min_value=0.1,
                max_value=2.0,
                value=1.0,
                step=0.1,
                help="Time scale parameter"
            )

        with col2:
            rho = st.slider(
                "Rho (ρ)",
                min_value=0.5,
                max_value=1.5,
                value=1.0,
                step=0.05,
                help="Maximum radius for UAV trajectory"
            )

            num_intervals = st.slider(
                "Intervals",
                min_value=100,
                max_value=5000,
                value=1000,
                step=100,
                help="Number of trajectory intervals"
            )

        # Visualization Options
        with st.expander("📈 Visualization Options"):
            viz_type = st.radio(
                "Visualization Library:",
                ["Matplotlib", "Plotly (Interactive)"],
                help="Choose between static or interactive plots"
            )

            color_scheme = st.selectbox(
                "Color Scheme:",
                ["hot", "viridis", "plasma", "inferno", "magma", "cividis"]
            )

        # Generate Button
        st.markdown("---")
        generate_btn = st.button(
            "🚀 Generate Distribution",
            type="primary",
            disabled=not api_key or not description
        )

    # Main Content Area
    if generate_btn:
        generate_distribution(
            description, delta, rho, tau, num_intervals,
            viz_type, color_scheme
        )

    # Display results
    if st.session_state.generated:
        display_results(viz_type)
    else:
        # Welcome message
        col1, col2, col3 = st.columns(3)
        with col1:
            st.info("💡 **Step 1**\nEnter your API key")
        with col2:
            st.info("📝 **Step 2**\nChoose or describe a distribution")
        with col3:
            st.info("🚀 **Step 3**\nClick Generate!")

        # Feature cards
        st.markdown("---")
        st.subheader("✨ Features")

        feat_col1, feat_col2, feat_col3 = st.columns(3)
        with feat_col1:
            st.markdown("""
            <div class="metric-card">
            <h4>🤖 AI-Powered</h4>
            <p>Uses LLM to generate custom distribution functions from natural language descriptions</p>
            </div>
            """, unsafe_allow_html=True)

        with feat_col2:
            st.markdown("""
            <div class="metric-card">
            <h4>📊 Rich Visualizations</h4>
            <p>6 comprehensive plots showing density, trajectories, and statistical distributions</p>
            </div>
            """, unsafe_allow_html=True)

        with feat_col3:
            st.markdown("""
            <div class="metric-card">
            <h4>⚡ Real-time Generation</h4>
            <p>Instant visualization with adjustable parameters and interactive plots</p>
            </div>
            """, unsafe_allow_html=True)

def generate_distribution(description, delta, rho, tau, num_intervals, viz_type, color_scheme):
    """Generate UAV distribution and visualizations"""

    progress_bar = st.progress(0)
    status_text = st.empty()

    try:
        # Step 1: Generate distribution
        status_text.text("🤖 Generating distribution with LLM...")
        progress_bar.progress(20)

        generator = LLMDistributionGenerator()
        dist_func, dist_name = generator.generate_distribution(description)

        st.session_state.distribution_name = dist_name
        status_text.text(f"✅ Generated: {dist_name}")
        progress_bar.progress(40)

    except Exception as e:
        status_text.text("⚠️ Using fallback distribution...")

        # Fallback distribution
        def dist_func(r, theta):
            x = r * np.cos(theta)
            return 4.0 * r / (2.5 * np.pi) if x >= 0 else 1.0 * r / (2.5 * np.pi)

        dist_name = "Eastern 4x Denser (Fallback)"
        st.session_state.distribution_name = dist_name
        progress_bar.progress(40)

    try:
        # Step 2: Create UAV system
        status_text.text("🔧 Creating UAV System...")
        progress_bar.progress(60)

        uav_system = ModularUAVSystem(
            distribution_func=dist_func,
            distribution_name=f"LLM: {dist_name}",
            delta=delta,
            rho=rho,
            tau=tau
        )

        # Step 3: Generate visualization
        status_text.text("📊 Generating visualizations...")
        progress_bar.progress(80)

        if viz_type == "Matplotlib":
            fig, trajectory, alphas = create_visualizations(
                uav_system, num_intervals, color_scheme
            )
            st.session_state.figure = fig
        else:
            fig, trajectory, alphas = create_plotly_visualizations(
                uav_system, num_intervals, color_scheme
            )
            st.session_state.figure = fig

        st.session_state.trajectory = trajectory
        st.session_state.generated = True

        progress_bar.progress(100)
        status_text.text("✨ Generation complete!")
        time.sleep(0.5)
        status_text.empty()
        progress_bar.empty()

    except Exception as e:
        st.error(f"Error: {str(e)}")
        progress_bar.empty()
        status_text.empty()

def display_results(viz_type):
    """Display generated results"""

    st.success(f"✅ Successfully generated: **{st.session_state.distribution_name}**")

    # Display metrics
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("📍 Trajectory Points", len(st.session_state.trajectory))
    with col2:
        st.metric("📊 Distribution Type", "LLM Generated")
    with col3:
        st.metric("⏱️ Generation Time", "< 5 seconds")
    with col4:
        if st.button("💾 Download Figure"):
            # Save figure logic here
            st.balloons()

    # Display visualizations
    st.markdown("---")
    st.subheader("📈 Visualization Results")

    if viz_type == "Matplotlib":
        st.pyplot(st.session_state.figure)
    else:
        st.plotly_chart(st.session_state.figure, use_container_width=True)

    # Additional analysis
    with st.expander("📊 Statistical Analysis"):
        trajectory = st.session_state.trajectory
        r_values = [pt[0] for pt in trajectory]

        col1, col2 = st.columns(2)
        with col1:
            st.markdown("**Radial Statistics:**")
            st.write(f"- Mean radius: {np.mean(r_values):.3f}")
            st.write(f"- Std deviation: {np.std(r_values):.3f}")
            st.write(f"- Min radius: {np.min(r_values):.3f}")
            st.write(f"- Max radius: {np.max(r_values):.3f}")

        with col2:
            # Simple histogram
            hist_fig, ax = plt.subplots(figsize=(6, 4))
            ax.hist(r_values, bins=50, alpha=0.7, color='blue', edgecolor='black')
            ax.set_xlabel('Radius')
            ax.set_ylabel('Frequency')
            ax.set_title('Radial Distribution')
            ax.grid(True, alpha=0.3)
            st.pyplot(hist_fig)

if __name__ == "__main__":
    main()