# -*- coding: utf-8 -*-
"""visualizations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHF94C5rMpFyq-kHA3IibeNaABABA2IX
"""

# ============================================
# FILE: src/visualizations.py
# ============================================
"""
Visualization Module
Creates static and interactive visualizations for UAV trajectories
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px

def create_visualizations(uav_system, num_intervals=500, color_scheme='hot'):
    """Create matplotlib visualizations"""

    # Generate trajectory
    trajectory, alphas = uav_system.generate_trajectory(num_intervals)

    # Process trajectory data
    r_values = [pt[0] for pt in trajectory]
    theta_values = [pt[1] for pt in trajectory]
    x_values = [r * np.cos(theta) for r, theta in zip(r_values, theta_values)]
    y_values = [r * np.sin(theta) for r, theta in zip(r_values, theta_values)]

    # Filter points within unit circle
    filtered_points = [(x, y, r, theta) for x, y, r, theta in
                      zip(x_values, y_values, r_values, theta_values)
                      if np.sqrt(x**2 + y**2) <= 1.0]
    if filtered_points:
        x_values, y_values, r_values, theta_values = zip(*filtered_points)
        x_values, y_values = list(x_values), list(y_values)

    # Create figure with subplots
    fig, axs = plt.subplots(3, 2, figsize=(14, 18))

    # 1. Position Density Heatmap
    heatmap, xedges, yedges = np.histogram2d(x_values, y_values,
                                             bins=100, range=[[-1.0, 1.0], [-1.0, 1.0]])
    x_centers = (xedges[:-1] + xedges[1:]) / 2
    y_centers = (yedges[:-1] + yedges[1:]) / 2
    X, Y = np.meshgrid(x_centers, y_centers)
    mask = X**2 + Y**2 > 1.0
    heatmap_masked = np.ma.masked_where(mask.T, heatmap.T)

    extent = [-1.0, 1.0, -1.0, 1.0]
    im = axs[0, 0].imshow(heatmap_masked, extent=extent, origin='lower',
                         cmap=color_scheme, norm=LogNorm(vmin=1, vmax=heatmap.max()),
                         interpolation='bilinear')
    axs[0, 0].add_artist(plt.Circle((0, 0), 1.0, fill=False, color='white', linewidth=2))
    axs[0, 0].add_artist(plt.Circle((0, 0), uav_system.delta, fill=False, color='cyan',
                                   linewidth=1, linestyle='--'))
    axs[0, 0].set_xlim(-1.1, 1.1)
    axs[0, 0].set_ylim(-1.1, 1.1)
    axs[0, 0].set_title('UAV Position Density', fontsize=14, fontweight='bold')
    axs[0, 0].set_xlabel('x')
    axs[0, 0].set_ylabel('y')
    axs[0, 0].set_aspect('equal')
    axs[0, 0].grid(True, alpha=0.2, linestyle=':', color='gray')
    fig.colorbar(im, ax=axs[0, 0], label='Count (log scale)')

    # 2. h_alpha function
    alpha_sample = uav_system.sample_alpha(1)[0]
    s_values = np.linspace(0, 1, 200)
    h_values = [uav_system.h_alpha(s, alpha_sample) for s in s_values]
    axs[0, 1].plot(s_values, h_values, 'b-', linewidth=2.5)
    axs[0, 1].fill_between(s_values, h_values, alpha=0.3)
    axs[0, 1].set_xlabel('s', fontsize=12)
    axs[0, 1].set_ylabel('h_alpha(s)', fontsize=12)
    axs[0, 1].set_title(f'h_alpha(s) for alpha = {alpha_sample:.3f}', fontsize=14, fontweight='bold')
    axs[0, 1].grid(True, alpha=0.3)

    # 3. h_alpha_inverse function
    t_values = np.linspace(0, uav_system.tau, 200)
    h_inv_values = [uav_system.h_alpha_inverse(t, alpha_sample) for t in t_values]
    axs[1, 0].plot(t_values, h_inv_values, 'g-', linewidth=2.5)
    axs[1, 0].fill_between(t_values, h_inv_values, alpha=0.3)
    axs[1, 0].set_xlabel('t', fontsize=12)
    axs[1, 0].set_ylabel('h_alpha_inv(t)', fontsize=12)
    axs[1, 0].set_title(f'h_alpha_inv(t) for alpha = {alpha_sample:.3f}', fontsize=14, fontweight='bold')
    axs[1, 0].grid(True, alpha=0.3)

    # 4. Alpha distribution
    axs[1, 1].hist(alphas, bins=50, density=True, alpha=0.7, color='purple', edgecolor='black')
    f_A_normalized = uav_system.f_A_values / np.trapz(uav_system.f_A_values, uav_system.alpha_range)
    axs[1, 1].plot(uav_system.alpha_range, f_A_normalized, 'r-', linewidth=2.5, label='True f_A(alpha)')
    axs[1, 1].set_title('Distribution of Sampled alpha', fontsize=14, fontweight='bold')
    axs[1, 1].set_xlabel('alpha', fontsize=12)
    axs[1, 1].set_ylabel('Density', fontsize=12)
    axs[1, 1].legend(fontsize=11)
    axs[1, 1].grid(True, alpha=0.3)

    # 5. Single trajectory
    single_traj = trajectory[:1000]
    x_single = [r * np.cos(theta) for r, theta in single_traj if r <= 1.0]
    y_single = [r * np.sin(theta) for r, theta in single_traj if r <= 1.0]
    valid_indices = [i for i, (r, theta) in enumerate(single_traj) if r <= 1.0]

    sc = axs[2, 0].scatter(x_single, y_single, c=valid_indices, cmap='viridis', s=2, alpha=0.8)
    axs[2, 0].add_artist(plt.Circle((0, 0), 1.0, fill=False, color='red', linewidth=2))
    axs[2, 0].add_artist(plt.Circle((0, 0), uav_system.delta, fill=False, color='orange',
                                   linewidth=1, linestyle='--'))
    axs[2, 0].set_xlim(-1.1, 1.1)
    axs[2, 0].set_ylim(-1.1, 1.1)
    axs[2, 0].set_title('Single UAV Trajectory', fontsize=14, fontweight='bold')
    axs[2, 0].set_xlabel('x', fontsize=12)
    axs[2, 0].set_ylabel('y', fontsize=12)
    axs[2, 0].set_aspect('equal')
    axs[2, 0].grid(True, alpha=0.2, linestyle=':', color='gray')
    fig.colorbar(sc, ax=axs[2, 0], label='Time Step')

    # 6. Radial distribution
    r_all = [r for r in r_values if r <= 1.0]
    axs[2, 1].hist(r_all, bins=50, density=True, alpha=0.7, color='blue', edgecolor='black')
    axs[2, 1].set_title('Radial Distribution', fontsize=14, fontweight='bold')
    axs[2, 1].set_xlabel('r', fontsize=12)
    axs[2, 1].set_ylabel('Density', fontsize=12)
    axs[2, 1].axvline(x=uav_system.delta, color='r', linestyle='--', linewidth=2,
                      label=f'delta = {uav_system.delta}')
    axs[2, 1].axvline(x=1.0,  color='g', linestyle='--', linewidth=2, label='rho = 1.0')
    axs[2, 1].set_xlim(0, 1.1)
    axs[2, 1].legend(fontsize=11)
    axs[2, 1].grid(True, alpha=0.3)

    plt.suptitle(f'{uav_system.distribution_name}', fontsize=18, fontweight='bold')
    plt.tight_layout()

    return fig, trajectory, alphas

def create_plotly_visualizations(uav_system, num_intervals=500, color_scheme='hot'):
    """Create interactive Plotly visualizations"""

    # Generate trajectory
    trajectory, alphas = uav_system.generate_trajectory(num_intervals)

    # Process trajectory data
    r_values = [pt[0] for pt in trajectory]
    theta_values = [pt[1] for pt in trajectory]
    x_values = [r * np.cos(theta) for r, theta in zip(r_values, theta_values)]
    y_values = [r * np.sin(theta) for r, theta in zip(r_values, theta_values)]

    # Create subplots
    fig = make_subplots(
        rows=3, cols=2,
        subplot_titles=('UAV Position Density', 'h_alpha(s) Function',
                       'h_alpha_inverse(t) Function', 'Alpha Distribution',
                       'Single UAV Trajectory', 'Radial Distribution'),
        specs=[[{'type': 'heatmap'}, {'type': 'scatter'}],
               [{'type': 'scatter'}, {'type': 'scatter'}],
               [{'type': 'scatter'}, {'type': 'bar'}]]
    )

    # 1. Position Density Heatmap
    heatmap, xedges, yedges = np.histogram2d(x_values, y_values,
                                             bins=100, range=[[-1.0, 1.0], [-1.0, 1.0]])

    fig.add_trace(
        go.Heatmap(z=heatmap.T, x=xedges, y=yedges,
                  colorscale=color_scheme, showscale=True),
        row=1, col=1
    )

    # Add circles
    theta_circle = np.linspace(0, 2*np.pi, 100)
    fig.add_trace(
        go.Scatter(x=np.cos(theta_circle), y=np.sin(theta_circle),
                  mode='lines', line=dict(color='white', width=2),
                  showlegend=False),
        row=1, col=1
    )

    # 2. h_alpha function
    alpha_sample = uav_system.sample_alpha(1)[0]
    s_values = np.linspace(0, 1, 200)
    h_values = [uav_system.h_alpha(s, alpha_sample) for s in s_values]

    fig.add_trace(
        go.Scatter(x=s_values, y=h_values, mode='lines',
                  fill='tozeroy', line=dict(color='blue', width=2)),
        row=1, col=2
    )

    # 3. h_alpha_inverse function
    t_values = np.linspace(0, uav_system.tau, 200)
    h_inv_values = [uav_system.h_alpha_inverse(t, alpha_sample) for t in t_values]

    fig.add_trace(
        go.Scatter(x=t_values, y=h_inv_values, mode='lines',
                  fill='tozeroy', line=dict(color='green', width=2)),
        row=2, col=1
    )

    # 4. Alpha distribution
    fig.add_trace(
        go.Histogram(x=alphas, nbinsx=50, histnorm='probability density',
                    marker=dict(color='purple', line=dict(color='black', width=1))),
        row=2, col=2
    )

    # 5. Single trajectory
    single_traj = trajectory[:1000]
    x_single = [r * np.cos(theta) for r, theta in single_traj if r <= 1.0]
    y_single = [r * np.sin(theta) for r, theta in single_traj if r <= 1.0]

    fig.add_trace(
        go.Scatter(x=x_single, y=y_single, mode='markers',
                  marker=dict(size=2, color=list(range(len(x_single))),
                            colorscale='viridis', showscale=True)),
        row=3, col=1
    )

    # 6. Radial distribution
    r_all = [r for r in r_values if r <= 1.0]

    fig.add_trace(
        go.Histogram(x=r_all, nbinsx=50, histnorm='probability density',
                    marker=dict(color='blue', line=dict(color='black', width=1))),
        row=3, col=2
    )

    # Update layout
    fig.update_layout(height=1200, showlegend=False,
                     title_text=f"{uav_system.distribution_name}",
                     title_font_size=20)

    # Update axes
    fig.update_xaxes(title_text="x", row=1, col=1)
    fig.update_yaxes(title_text="y", row=1, col=1)
    fig.update_xaxes(title_text="s", row=1, col=2)
    fig.update_yaxes(title_text="h_alpha(s)", row=1, col=2)
    fig.update_xaxes(title_text="t", row=2, col=1)
    fig.update_yaxes(title_text="h_alpha_inv(t)", row=2, col=1)
    fig.update_xaxes(title_text="alpha", row=2, col=2)
    fig.update_yaxes(title_text="Density", row=2, col=2)
    fig.update_xaxes(title_text="x", row=3, col=1)
    fig.update_yaxes(title_text="y", row=3, col=1)
    fig.update_xaxes(title_text="r", row=3, col=2)
    fig.update_yaxes(title_text="Density", row=3, col=2)

    return fig, trajectory, alphas

# ============================================
# FILE: src/__init__.py
# ============================================
"""
UAV Distribution Generator Package
"""

from .llm_generator import LLMDistributionGenerator
from .uav_system import ModularUAVSystem
from .visualizations import create_visualizations, create_plotly_visualizations

__all__ = [
    'LLMDistributionGenerator',
    'ModularUAVSystem',
    'create_visualizations',
    'create_plotly_visualizations'
]

# ============================================
# FILE: requirements.txt
# ============================================
streamlit>=1.28.0
numpy>=1.24.0
matplotlib>=3.6.0
scipy>=1.10.0
plotly>=5.17.0
requests>=2.31.0
Pillow>=10.0.0

# ============================================
# FILE: .gitignore
# ============================================
# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST

# Virtual Environment
venv/
ENV/
env/
.venv

# IDE
.vscode/
.idea/
*.swp
*.swo
*~
.DS_Store

# Streamlit
.streamlit/secrets.toml

# Environment variables
.env
.env.local

# Output files
*.png
*.jpg
*.pdf
*.svg

# Logs
*.log

# ============================================
# FILE: README.md
# ============================================
# 🚁 UAV Distribution Generator

[![Streamlit App](https://static.streamlit.io/badges/streamlit_badge_black_white.svg)](https://your-app-url.streamlit.app)
[![Python 3.8+](https://img.shields.io/badge/python-3.8+-blue.svg)](https://www.python.org/downloads/)
[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)

An AI-powered UAV trajectory generator that creates custom spatial distributions using Large Language Models (LLMs) and visualizes complex flight patterns.

![UAV Distribution Demo](demo.gif)

## ✨ Features

- **🤖 AI-Powered Generation**: Uses Groq LLM API to generate distribution functions from natural language descriptions
- **📊 Rich Visualizations**: 6 comprehensive plots showing density, trajectories, and statistical distributions
- **🎯 Custom Distributions**: Create any spatial distribution pattern through simple text descriptions
- **⚡ Real-time Generation**: Instant visualization with adjustable parameters
- **🌐 Web Interface**: Clean, modern Streamlit interface accessible from any browser
- **📈 Interactive Plots**: Choose between Matplotlib (static) or Plotly (interactive) visualizations

## 🚀 Quick Start

### Online Demo
Visit our live demo at: [https://your-app-url.streamlit.app](https://your-app-url.streamlit.app)

### Local Installation

1. **Clone the repository**
```bash
git clone https://github.com/yourusername/uav-distribution-generator.git
cd uav-distribution-generator
```

2. **Create a virtual environment** (recommended)
```bash
python -m venv venv
source venv/bin/activate  # On Windows: venv\Scripts\activate
```

3. **Install dependencies**
```bash
pip install -r requirements.txt
```

4. **Get your Groq API Key**
   - Visit [console.groq.com](https://console.groq.com)
   - Create an account and generate an API key
   - Keep it ready for the app

5. **Run the Streamlit app**
```bash
streamlit run app.py
```

6. **Open your browser**
   - Navigate to `http://localhost:8501`
   - Enter your API key and start generating!

## 📖 Usage

### Basic Usage

1. **Enter your Groq API key** in the sidebar
2. **Choose a distribution**:
   - Select from 7 preset distributions, or
   - Write your own custom description
3. **Adjust parameters**:
   - **Delta (δ)**: Minimum radius (0.01-0.3)
   - **Rho (ρ)**: Maximum radius (0.5-1.5)
   - **Tau (τ)**: Time scale (0.1-2.0)
   - **Intervals**: Number of trajectory points (100-5000)
4. **Click "Generate Distribution"**
5. **View results** and download the figure

### Example Distributions

- **"Eastern 4x Denser"**: Higher density in the right half of the circle
- **"Center Hotspot"**: Concentrated activity in the center
- **"Ring Pattern"**: Dense ring formation at specific radius
- **"Dual Hotspots"**: Two areas of high activity
- **Custom**: "Create a spiral pattern with increasing density towards the center"

## 🏗️ Project Structure

```
uav-distribution-generator/
├── app.py                 # Main Streamlit application
├── src/
│   ├── __init__.py       # Package initialization
│   ├── llm_generator.py  # LLM integration module
│   ├── uav_system.py     # Core UAV system logic
│   └── visualizations.py # Plotting functions
├── requirements.txt      # Python dependencies
├── README.md            # Documentation
├── LICENSE              # MIT License
└── .gitignore          # Git ignore rules
```

## 🔧 Configuration

### Environment Variables

Create a `.env` file in the root directory:

```env
GROQ_API_KEY=your_api_key_here
```

### Streamlit Configuration

Create `.streamlit/config.toml`:

```toml
[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 10
enableCORS = false
```

## 📊 Technical Details

### Algorithm Overview

1. **Distribution Generation**: LLM converts text descriptions into mathematical functions
2. **Grid Precomputation**: Efficient sampling through precomputed distribution grids
3. **Trajectory Generation**: Modular system based on transformation functions
4. **Visualization**: Multiple perspectives including density heatmaps and trajectory plots

### Key Parameters

- **Distribution Function**: `f(r, θ)` - Probability density in polar coordinates
- **Transformation Functions**:
  - `G(s)`: Maps unit interval to radius
  - `Φ(s)`: Maps to angular displacement
  - `h_α(s)`: Time transformation function

## 🤝 Contributing

Contributions are welcome! Please feel free to submit a Pull Request.

1. Fork the repository
2. Create your feature branch (`git checkout -b feature/AmazingFeature`)
3. Commit your changes (`git commit -m 'Add some AmazingFeature'`)
4. Push to the branch (`git push origin feature/AmazingFeature`)
5. Open a Pull Request

## 📝 License

This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.

## 🙏 Acknowledgments

- Groq for providing the LLM API
- Streamlit for the web framework
- The scientific Python community for excellent libraries

## 📧 Contact

Your Name - [@yourtwitter](https://twitter.com/yourtwitter) - email@example.com

Project Link: [https://github.com/yourusername/uav-distribution-generator](https://github.com/yourusername/uav-distribution-generator)

## 🐛 Troubleshooting

### Common Issues

1. **API Key Error**: Ensure your Groq API key is valid and has sufficient credits
2. **Import Errors**: Run `pip install -r requirements.txt` to install all dependencies
3. **Memory Issues**: Reduce the number of intervals if running on limited resources
4. **Visualization Not Loading**: Try switching between Matplotlib and Plotly modes

### Getting Help

- Open an issue on GitHub
- Check existing issues for solutions
- Contact the maintainers

---

Made with ❤️ by [Your Name]

# ============================================
# FILE: LICENSE
# ============================================
MIT License

Copyright (c) 2024 [Your Name]

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

# ============================================
# FILE: setup.py (optional for package distribution)
# ============================================
from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="uav-distribution-generator",
    version="1.0.0",
    author="Your Name",
    author_email="your.email@example.com",
    description="AI-powered UAV trajectory generator with custom spatial distributions",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/uav-distribution-generator",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.8",
    install_requires=[
        "streamlit>=1.28.0",
        "numpy>=1.24.0",
        "matplotlib>=3.6.0",
        "scipy>=1.10.0",
        "plotly>=5.17.0",
        "requests>=2.31.0",
        "Pillow>=10.0.0",
    ],
    entry_points={
        "console_scripts": [
            "uav-generator=app:main",
        ],
    },
)