# -*- coding: utf-8 -*-
"""llm_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Z3J2ns79ce946dhaNUidkiBx3jYs_yf
"""

"""
LLM Distribution Generator Module
Handles AI-powered distribution function generation
"""

import os
import re
import numpy as np
import requests
import json
from typing import Callable, Tuple

class LLMDistributionGenerator:
    """Generate distribution functions using LLM"""

    def __init__(self, provider: str = "groq", api_key: str = None, model: str = None):
        self.provider = provider.lower()
        if self.provider == "groq":
            self.api_key = api_key or os.environ.get("GROQ_API_KEY")
            if not self.api_key:
                raise ValueError("Groq API key required. Set GROQ_API_KEY environment variable or pass api_key parameter.")
            self.model = model or "llama-3.3-70b-versatile"
            self.api_url = "https://api.groq.com/openai/v1/chat/completions"

    def generate_distribution(self, description: str) -> Tuple[Callable, str]:
        """
        Generate a distribution function from natural language description

        Args:
            description: Natural language description of the desired distribution

        Returns:
            Tuple of (distribution_function, distribution_name)
        """
        prompt = self._create_prompt(description)
        response_text = self._call_groq(prompt)
        function_code, dist_name = self._parse_response(response_text)
        distribution_func = self._execute_code(function_code)
        return distribution_func, dist_name

    def _call_groq(self, prompt: str) -> str:
        """Call Groq API to generate distribution code"""
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }

        data = {
            "model": self.model,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.3,
            "max_tokens": 2048
        }

        response = requests.post(self.api_url, headers=headers, json=data)
        if response.status_code != 200:
            raise ValueError(f"Groq API error: {response.text}")

        return response.json()["choices"][0]["message"]["content"]

    def _create_prompt(self, description: str) -> str:
        """Create prompt for LLM to generate distribution function"""
        return f"""You are a Python code generator for spatial probability distributions. Generate a distribution function based on the following description:

"{description}"

Requirements:
1. Create a Python function named `generated_distribution(r, theta)` that:
   - Takes polar coordinates (r, theta) as inputs
   - Returns the probability density at that point
   - r is in range [0, 1] (unit circle)
   - theta is in range [0, 2π]

2. The function must:
   - Return positive values (or zero)
   - Be a valid probability density
   - Use numpy functions (imported as np)
   - Handle edge cases gracefully

3. Also provide a descriptive name for this distribution

Output format:
```python
def generated_distribution(r, theta):
    # Your implementation here
    return density_value
```

DISTRIBUTION_NAME: [One line description]

Example:
```python
def generated_distribution(r, theta):
    if 0 <= theta < np.pi:
        return 2.0 * r / np.pi
    else:
        return 0.5 * r / np.pi
```
DISTRIBUTION_NAME: Northern Hemisphere Enhanced

Now generate the code for: {description}"""

    def _parse_response(self, response: str) -> Tuple[str, str]:
        """Parse LLM response to extract code and distribution name"""
        # Extract code block
        code_match = re.search(r'```python\n(.*?)```', response, re.DOTALL)
        if not code_match:
            raise ValueError("Could not find Python code block in LLM response")

        function_code = code_match.group(1).strip()

        # Clean up code
        function_code = re.sub(r'\n\s*DISTRIBUTION_NAME:.*$', '', function_code, flags=re.MULTILINE)
        function_code = re.sub(r'^import .*$', '', function_code, flags=re.MULTILINE)
        function_code = re.sub(r'^from .* import .*$', '', function_code, flags=re.MULTILINE)
        function_code = re.sub(r'\n\n+', '\n\n', function_code).strip()

        # Extract distribution name
        name_match = re.search(r'DISTRIBUTION_NAME:\s*(.+)', response)
        dist_name = name_match.group(1).strip() if name_match else "LLM Generated Distribution"

        return function_code, dist_name

    def _execute_code(self, code: str) -> Callable:
        """Execute generated code and return function"""
        # Create safe namespace
        namespace = {
            'np': np,
            '__builtins__': {
                'range': range,
                'len': len,
                'abs': abs,
                'min': min,
                'max': max,
                'sum': sum,
                'float': float,
                'int': int,
                'True': True,
                'False': False
            }
        }

        # Execute code in namespace
        exec(code, namespace)

        # Check if function was created
        if 'generated_distribution' not in namespace:
            raise ValueError("Generated code must define 'generated_distribution' function")

        func = namespace['generated_distribution']

        # Validate function
        self._validate_function(func)

        return func

    def _validate_function(self, func: Callable):
        """Validate that the generated function works correctly"""
        test_points = [
            (0.5, 0.0),
            (0.5, np.pi/2),
            (0.5, np.pi),
            (0.5, 3*np.pi/2),
            (0.1, 0.0),
            (0.9, np.pi)
        ]

        for r, theta in test_points:
            try:
                result = func(r, theta)

                # Check if result is numeric
                if not isinstance(result, (int, float, np.number)):
                    raise ValueError(f"Function returned non-numeric value: {type(result)}")

                # Check if result is non-negative
                if result < 0:
                    raise ValueError(f"Function returned negative value: {result}")

                # Check if result is finite
                if not np.isfinite(result):
                    raise ValueError(f"Function returned non-finite value: {result}")

            except Exception as e:
                raise ValueError(f"Function failed at (r={r}, θ={theta}): {str(e)}")
