# -*- coding: utf-8 -*-
"""uav_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_oGMeAz1eLTvcUWEYQb7iDtzK_YE-SYs
"""

"""
UAV System Module
Core UAV trajectory generation and distribution system
"""

import numpy as np
from scipy.interpolate import PchipInterpolator, interp1d, RegularGridInterpolator
from typing import Callable, Tuple, List

def _wrap_alpha(α, αmin, αmax):
    """Wrap alpha value to valid range"""
    return (α - αmin) % (αmax - αmin) + αmin

class ModularUAVSystem:
    """
    Modular UAV System for trajectory generation based on probability distributions
    """

    def __init__(self, distribution_func: Callable, distribution_name: str,
                 delta: float = 0.1, rho: float = 1.0, tau: float = 1.0):
        """
        Initialize UAV System

        Args:
            distribution_func: Function that takes (r, theta) and returns probability density
            distribution_name: Name of the distribution
            delta: Minimum radius parameter
            rho: Maximum radius parameter
            tau: Time scale parameter
        """
        self.f_R_Theta = distribution_func
        self.distribution_name = distribution_name
        self.delta = float(delta)
        self.rho = float(rho)
        self.tau = float(tau)

        # System parameters
        self.phi_max = 0.1 * np.pi
        self.Phi = lambda s: self.phi_max * s
        self.G = lambda s: (self.rho - self.delta) * s**2 + self.delta
        self.G_inv = lambda r: np.sqrt((r - self.delta) / (self.rho - self.delta))

        # Alpha range
        self.alpha_min = -0.1 * np.pi
        self.alpha_max = 2 * np.pi

        # Setup distribution
        self._setup_distribution()

    def _setup_distribution(self):
        """Precompute distribution grids for efficient sampling"""
        # Grid parameters
        n_b = 256
        n_alpha = 1440

        # Create grids
        b_grid = np.linspace(self.delta, self.rho, n_b)
        alpha_grid = np.linspace(self.alpha_min, self.alpha_max, n_alpha, endpoint=False)

        # Compute s values for b grid
        s_of_b = np.sqrt((b_grid - self.delta) / (self.rho - self.delta))
        theta_base = self.Phi(s_of_b)

        # Compute joint distribution f(b, alpha)
        f_BA = np.empty((n_b, n_alpha), dtype=float)
        for j, α in enumerate(alpha_grid):
            θ = (theta_base + α) % (2*np.pi)
            vals = [self.f_R_Theta(bi, th) for bi, th in zip(b_grid, θ)]
            f_BA[:, j] = np.maximum(vals, 0.0)

        # Compute marginal distribution f(alpha)
        f_A = np.trapz(f_BA, b_grid, axis=0)
        dα = (self.alpha_max - self.alpha_min) / n_alpha
        Zα = f_A.sum() * dα

        if Zα <= 0:
            raise ValueError("Distribution integrates to zero")

        f_A /= Zα

        # Compute CDF for alpha
        CDF_A = np.cumsum(f_A) * dα
        CDF_A[-1] = 1.0
        CDF_A = np.maximum.accumulate(CDF_A)

        # Create inverse CDF interpolator for sampling
        cdf_u, idx = np.unique(CDF_A, return_index=True)
        alpha_u = alpha_grid[idx]
        self.inverse_cdf = PchipInterpolator(cdf_u, alpha_u, extrapolate=True)

        # Compute conditional distribution f(b|alpha)
        f_B_given_A = f_BA / np.maximum(f_A[None, :], 1e-16)

        # Compute conditional CDF F(b|alpha)
        db = np.diff(np.hstack([b_grid[0], b_grid]))
        F = np.cumsum(0.5*(np.vstack([f_B_given_A[0,:], f_B_given_A[:-1,:]]) + f_B_given_A) * db[:,None], axis=0)
        F /= np.maximum(F[-1,:], 1e-16)[None, :]

        # Pad for periodic boundary conditions
        pad = 2
        α_pad = np.concatenate([
            alpha_grid[-pad:] - (self.alpha_max - self.alpha_min),
            alpha_grid,
            alpha_grid[:pad] + (self.alpha_max - self.alpha_min)
        ])
        F_pad = np.hstack([F[:, -pad:], F, F[:, :pad]])

        # Create interpolator
        self.F_interp = RegularGridInterpolator(
            (b_grid, α_pad), F_pad,
            bounds_error=False, fill_value=None, method='linear'
        )

        # Store for later use
        self.b_grid = b_grid
        self.alpha_range = alpha_grid
        self.f_A_values = f_A
        self.cdf_values = CDF_A
        self.f_A_interp = interp1d(alpha_grid, f_A, kind='linear', bounds_error=False, fill_value=0.0)

    def sample_alpha(self, n_samples: int = 1) -> np.ndarray:
        """Sample alpha values from the distribution"""
        u = np.random.uniform(0, 1, n_samples)
        return self.inverse_cdf(u)

    def compute_F_B_A(self, b: float, alpha: float) -> float:
        """Compute conditional CDF F(b|alpha)"""
        bq = float(np.clip(b, self.delta, self.rho))
        αq = float(_wrap_alpha(alpha, self.alpha_min, self.alpha_max))
        val = float(self.F_interp([[bq, αq]])[0])
        return np.clip(val, 0.0, 1.0)

    def h_alpha(self, s: float, alpha: float) -> float:
        """Compute h_alpha(s) function"""
        b = self.G(s)
        return self.tau * self.compute_F_B_A(b, alpha)

    def get_b_min_max(self, alpha: float) -> Tuple[float, float]:
        """Get valid b range for given alpha"""
        eps = 1e-10

        if -np.pi/10 - eps <= alpha <= 0 + eps:
            b_min = max(0, (-10 * alpha) / np.pi)
            b_max = 1
        elif 0 < alpha <= 9*np.pi/10 + eps:
            b_min = 0
            b_max = 1
        elif 9*np.pi/10 < alpha <= np.pi + eps:
            b_min = 0
            b_max = 1
        elif np.pi < alpha <= 19*np.pi/10 + eps:
            b_min = 0
            b_max = 1
        elif 19*np.pi/10 < alpha <= 2*np.pi + eps:
            b_min = 0
            b_max = max(0, (2 * np.pi - alpha) * 10 / np.pi)
        else:
            alpha_wrapped = alpha % (2*np.pi)
            if alpha_wrapped < -np.pi/10 - eps:
                alpha_wrapped += 2*np.pi
            return self.get_b_min_max(alpha_wrapped)

        return b_min, b_max

    def h_alpha_inverse(self, t: float, alpha: float, epsilon: float = 1e-10,
                        max_iterations: int = 100) -> float:
        """Compute inverse of h_alpha function using binary search"""
        s_min, s_max = self.get_b_min_max(alpha)

        if t <= 0:
            return s_min
        if t >= self.tau:
            return s_max

        if s_max - s_min < epsilon:
            return (s_min + s_max) / 2

        h_min = self.h_alpha(s_min, alpha)
        h_max = self.h_alpha(s_max, alpha)

        if t <= h_min:
            return s_min
        if t >= h_max:
            return s_max

        # Binary search
        lower, upper = s_min, s_max

        for _ in range(max_iterations):
            mid = 0.5 * (lower + upper)
            h_mid = self.h_alpha(mid, alpha)

            if abs(h_mid - t) < epsilon:
                return mid

            if h_mid < t:
                lower = mid
            else:
                upper = mid

        return 0.5 * (lower + upper)

    def generate_trajectory(self, num_intervals: int = 100) -> Tuple[List, List]:
        """
        Generate UAV trajectory

        Args:
            num_intervals: Number of time intervals

        Returns:
            Tuple of (trajectory points, alpha values)
        """
        trajectory = []
        alphas = []

        for _ in range(num_intervals):
            # Sample alpha
            alpha_k = self.sample_alpha(1)[0]
            alphas.append(alpha_k)

            # Generate trajectory for this interval
            t_values = np.linspace(0, self.tau, 100)
            for t in t_values:
                s = self.h_alpha_inverse(t, alpha_k)
                r = self.G(s)
                theta = self.Phi(s) + alpha_k
                trajectory.append((r, theta))

        return trajectory, alphas
